### ISSUE TITLE
Please add a license to the code

### ISSUE THREAD

**Issue by dashorst** [bsutton/BattlefieldJava#1]
I've been searching for the coderuler code to do some AI algorithm stuff myself, and came across this project. I would like to do some work with it, but the project doesn't have a license. This means that I can't do anything with it (i.e. fork and work on it).

Could you pick one of the open source licenses available? If you need help: https://choosealicense.com is a good source for picking one.

Thanks!

**Comment by bsutton** [comment]
done.
